(function(){
var $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s)),KEY="guitarCoachV1",defaults={days:{},totalMinutes:0,totalSwitches:0,tunerSessions:0,bestSwitch:null,lastActive:null},data=load();
function dateKey(d){d=d||new Date();return d.toISOString().slice(0,10)}
function load(){try{return Object.assign({},defaults,JSON.parse(localStorage.getItem(KEY)||"{}"))}catch(e){return Object.assign({},defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderAll()}
function today(){var k=dateKey();if(!data.days[k])data.days[k]={tasks:[false,false,false,false],minutes:0,switches:0};return data.days[k]}
function toast(m){var e=$("#toast");e.textContent=m;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),1600)}
function go(n){$$(".page").forEach(p=>p.classList.remove("active"));$("#page-"+n).classList.add("active");$$(".nav").forEach(b=>b.classList.toggle("active",b.dataset.page===n));window.scrollTo({top:0,behavior:"smooth"})}
var tasks=[{name:"調音",desc:"確認六條弦音準",min:2,go:"tuner"},{name:"和弦暖身",desc:"C / G / Am / Em 各按 5 次",min:5,go:"chords"},{name:"換和弦",desc:"連續切換至少 20 次",min:5,go:"chords"},{name:"節奏練習",desc:"70 BPM 穩定刷弦",min:8,go:"metro"}];
function completed(){return today().tasks.filter(Boolean).length}
function streak(){var ds=Object.keys(data.days).filter(k=>data.days[k].tasks&&data.days[k].tasks.some(Boolean)).sort();if(!ds.length)return 0;var n=0,d=new Date();if(ds.indexOf(dateKey())<0)d.setDate(d.getDate()-1);while(ds.indexOf(dateKey(d))>=0){n++;d.setDate(d.getDate()-1)}return n}
function advice(){var d=completed();if(!d)return"今天先從調音開始。第一次不用追速度，目標是把每個聲音彈乾淨。";if(d<3)return"今天有進度了。下一個重點放在和弦切換，慢沒關係，先讓手指一起移動。";if(data.bestSwitch&&data.bestSwitch<1.8)return"你最快換和弦約 "+data.bestSwitch.toFixed(1)+" 秒，可以開始搭配 70–80 BPM 節拍器。";if(data.totalSwitches>=60)return"和弦切換量已累積不少，下一步把 C、G、Am、Em 放進固定節拍裡循環。";return"先維持穩定與乾淨，能連續成功 3 次再提高 BPM。"}
function renderTasks(){var d=today();$("#taskList").innerHTML=tasks.map((t,i)=>'<div class="task"><input type="checkbox" data-task="'+i+'" '+(d.tasks[i]?"checked":"")+'><div class="taskMain"><strong>'+t.name+'</strong><span>'+t.desc+'</span></div><button class="pill" data-go="'+t.go+'">'+t.min+' 分</button></div>').join("");$$("[data-task]").forEach(c=>c.onchange=()=>{var i=+c.dataset.task,day=today(),was=day.tasks[i];day.tasks[i]=c.checked;if(!was&&c.checked){day.minutes+=tasks[i].min;data.totalMinutes+=tasks[i].min;data.lastActive=dateKey()}if(was&&!c.checked){day.minutes=Math.max(0,day.minutes-tasks[i].min);data.totalMinutes=Math.max(0,data.totalMinutes-tasks[i].min)}save()});$$("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go))}
function renderHome(){var d=completed(),p=Math.round(d/tasks.length*100);$("#todayPct").textContent=p+"%";$("#todayBar").style.width=p+"%";$("#doneText").textContent=d+" / "+tasks.length+" 項";$("#streakChip").textContent="連續 "+streak()+" 天";$("#aiAdvice").textContent=advice();$("#coachLine").textContent=d===4?"今天課表完成。可以自由練一首喜歡的歌收尾。":"先把吉他調準，再花 20 分鐘把基本功練穩。"}
function renderProgress(){var a=Object.keys(data.days).filter(k=>data.days[k].tasks&&data.days[k].tasks.some(Boolean)).length;$("#statDays").textContent=a;$("#statMinutes").textContent=data.totalMinutes||0;$("#statSwitches").textContent=data.totalSwitches||0;$("#progressAdvice").textContent=advice();var ks=Object.keys(data.days).sort().reverse().slice(0,14);$("#historyList").innerHTML=ks.length?ks.map(k=>{var d=data.days[k],n=d.tasks?d.tasks.filter(Boolean).length:0,dt=new Date(k+"T00:00:00");return'<div style="display:flex;justify-content:space-between;gap:12px;padding:9px 0;border-bottom:1px solid #e2e8f0"><span>'+(dt.getMonth()+1)+'/'+dt.getDate()+'</span><span>'+n+'/4 項 · '+(d.minutes||0)+' 分 · '+(d.switches||0)+' 次</span></div>'}).join(""):"還沒有紀錄。"}
function renderAll(){renderTasks();renderHome();renderProgress()}
$$(".nav").forEach(b=>b.onclick=()=>go(b.dataset.page));$$(".quick").forEach(b=>b.onclick=()=>go(b.dataset.go));
$("#resetToday").onclick=()=>{var d=today();data.totalMinutes=Math.max(0,data.totalMinutes-(d.minutes||0));data.days[dateKey()]={tasks:[false,false,false,false],minutes:0,switches:0};save();toast("今日練習已重新開始")};
$("#clearData").onclick=()=>{if(confirm("確定要清除所有練習紀錄嗎？")){localStorage.removeItem(KEY);data=JSON.parse(JSON.stringify(defaults));today();save();toast("已清除所有紀錄")}};

var strings=[{name:"E2",freq:82.41},{name:"A2",freq:110},{name:"D3",freq:146.83},{name:"G3",freq:196},{name:"B3",freq:246.94},{name:"E4",freq:329.63}],target=null;
$("#stringGrid").innerHTML=strings.map((s,i)=>'<button data-string="'+i+'">'+s.name+'</button>').join("");
$$("[data-string]").forEach(b=>b.onclick=()=>{target=strings[+b.dataset.string];$$("[data-string]").forEach(x=>x.classList.toggle("active",x===b));toast("目標："+target.name)});
var actx,analyser,stream,raf,buf,notes=["C","C♯","D","D♯","E","F","F♯","G","G♯","A","A♯","B"];
function correlate(a,sr){var n=a.length,r=0,i,j;for(i=0;i<n;i++)r+=a[i]*a[i];r=Math.sqrt(r/n);if(r<.01)return-1;var c=new Array(n).fill(0);for(i=0;i<n;i++)for(j=0;j<n-i;j++)c[i]+=a[j]*a[j+i];var d=0;while(d+1<n&&c[d]>c[d+1])d++;var mv=-1,mp=-1;for(i=d;i<n;i++)if(c[i]>mv){mv=c[i];mp=i}if(mp<=0)return-1;var x1=c[mp-1]||0,x2=c[mp]||0,x3=c[mp+1]||0,A=(x1+x3-2*x2)/2,B=(x3-x1)/2,T=mp;if(A)T=T-B/(2*A);return sr/T}
function noteOf(f){var e=69+12*Math.log2(f/440),m=Math.round(e),c=Math.round((e-m)*100),o=Math.floor(m/12)-1;return{name:notes[(m%12+12)%12]+o,cents:c}}
function tunerTick(){analyser.getFloatTimeDomainData(buf);var f=correlate(buf,actx.sampleRate);if(f>60&&f<500){var n=noteOf(f),c=n.cents,name=n.name;if(target){c=Math.round(1200*Math.log2(f/target.freq));while(c>50)c-=1200;while(c<-50)c+=1200;name=target.name}c=Math.max(-50,Math.min(50,c));$("#noteName").textContent=name;$("#freqText").textContent=f.toFixed(1)+" Hz";$("#needle").style.transform="translateX("+(c*2.4)+"px)";if(Math.abs(c)<=5){$("#tuneStatus").textContent="音準很好";$("#tuneStatus").style.color="#0f766e"}else{$("#tuneStatus").textContent=(c<0?"偏低 ":"偏高 ")+Math.abs(c)+" cents";$("#tuneStatus").style.color="#b45309"}}else{$("#freqText").textContent="請撥一條弦";$("#tuneStatus").textContent="等待聲音"}raf=requestAnimationFrame(tunerTick)}
$("#tunerStart").onclick=async()=>{try{actx=new(window.AudioContext||window.webkitAudioContext)();stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});var src=actx.createMediaStreamSource(stream);analyser=actx.createAnalyser();analyser.fftSize=2048;buf=new Float32Array(analyser.fftSize);src.connect(analyser);$("#tunerStart").classList.add("hidden");$("#tunerStop").classList.remove("hidden");$("#micHint").classList.add("hidden");data.tunerSessions=(data.tunerSessions||0)+1;save();tunerTick()}catch(e){$("#tuneStatus").textContent="無法使用麥克風";toast("請確認瀏覽器已允許麥克風權限")}};
$("#tunerStop").onclick=()=>{cancelAnimationFrame(raf);if(stream)stream.getTracks().forEach(t=>t.stop());if(actx)actx.close();$("#tunerStart").classList.remove("hidden");$("#tunerStop").classList.add("hidden");$("#noteName").textContent="—";$("#freqText").textContent="等待麥克風";$("#tuneStatus").textContent="尚未開始";$("#needle").style.transform="translateX(0)"};

var metroCtx,metroTimer,metroOn=false,bpm=70,taps=[];
function setBpm(v){bpm=Math.max(40,Math.min(200,Math.round(v)));$("#bpmText").textContent=bpm;$("#bpmRange").value=bpm;if(metroOn){stopMetro();startMetro()}}
function click(){if(!metroCtx)metroCtx=new(window.AudioContext||window.webkitAudioContext)();var o=metroCtx.createOscillator(),g=metroCtx.createGain();o.frequency.value=1000;g.gain.setValueAtTime(.22,metroCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,metroCtx.currentTime+.05);o.connect(g).connect(metroCtx.destination);o.start();o.stop(metroCtx.currentTime+.05);$("#pulse").classList.add("on");setTimeout(()=>$("#pulse").classList.remove("on"),80)}
function startMetro(){metroOn=true;$("#metroToggle").textContent="停止";click();metroTimer=setInterval(click,60000/bpm)}
function stopMetro(){metroOn=false;$("#metroToggle").textContent="開始";clearInterval(metroTimer);metroTimer=null}
$("#bpmRange").oninput=e=>setBpm(e.target.value);$$("[data-bpm]").forEach(b=>b.onclick=()=>setBpm(+b.dataset.bpm));$("#metroToggle").onclick=()=>metroOn?stopMetro():startMetro();$("#tapBtn").onclick=()=>{var now=performance.now();taps.push(now);if(taps.length>6)taps.shift();if(taps.length>=2){var ds=taps.slice(1).map((t,i)=>t-taps[i]),avg=ds.reduce((a,b)=>a+b,0)/ds.length;setBpm(60000/avg)}toast("繼續照速度點按")};

var chords={C:{frets:["x",3,2,0,1,0],f:[0,3,2,0,1,0]},G:{frets:[3,2,0,0,0,3],f:[2,1,0,0,0,3]},Am:{frets:["x",0,2,2,1,0],f:[0,0,2,3,1,0]},Em:{frets:[0,2,2,0,0,0],f:[0,2,3,0,0,0]},F:{frets:[1,3,3,2,1,1],f:[1,3,4,2,1,1],barre:1},Dm:{frets:["x","x",0,2,3,1],f:[0,0,0,2,3,1]}},names=Object.keys(chords),seq=[],idx=0,last=performance.now(),times=[],count=0;
function draw(name){var c=$("#chordCanvas"),x=c.getContext("2d"),d=chords[name],L=65,T=42,W=190,H=165,sg=W/5,fg=H/5;x.clearRect(0,0,c.width,c.height);x.strokeStyle="#0f172a";x.fillStyle="#0f172a";x.textAlign="center";x.textBaseline="middle";x.lineCap="round";for(var i=0;i<6;i++){var xx=L+i*sg;x.lineWidth=2;x.beginPath();x.moveTo(xx,T);x.lineTo(xx,T+H);x.stroke()}for(i=0;i<=5;i++){var yy=T+i*fg;x.lineWidth=i===0?5:2;x.beginPath();x.moveTo(L,yy);x.lineTo(L+W,yy);x.stroke()}x.font="16px sans-serif";d.frets.forEach((fr,i)=>{var xx=L+i*sg;if(fr==="x")x.fillText("×",xx,18);else if(fr===0){x.beginPath();x.arc(xx,18,7,0,Math.PI*2);x.stroke()}else{var yy=T+(fr-.5)*fg;x.beginPath();x.arc(xx,yy,12,0,Math.PI*2);x.fill();if(d.f[i]){x.fillStyle="#fff";x.font="12px sans-serif";x.fillText(d.f[i],xx,yy+1);x.fillStyle="#0f172a";x.font="16px sans-serif"}}});if(d.barre){x.lineWidth=18;x.beginPath();x.moveTo(L+2,T+.5*fg);x.lineTo(L+W-2,T+.5*fg);x.stroke()}x.fillStyle="#64748b";x.font="11px sans-serif";["6","5","4","3","2","1"].forEach((s,i)=>x.fillText(s,L+i*sg,T+H+24))}
function newSeq(){seq=[];while(seq.length<4){var c=names[Math.floor(Math.random()*names.length)];if(!seq.length||seq[seq.length-1]!==c)seq.push(c)}idx=0;count=0;times=[];last=performance.now();updateChord()}
function updateChord(){var n=seq[idx];$("#chordName").textContent=n;draw(n);$("#sequence").innerHTML=seq.map((c,i)=>'<span class="'+(i===idx?"current":"")+'">'+c+'</span>').join("");$("#switchCount").textContent=count;$("#switchTime").textContent=(times.length?times.reduce((a,b)=>a+b,0)/times.length:0).toFixed(1);$("#bestTime").textContent=data.bestSwitch?data.bestSwitch.toFixed(1):"—"}
$("#nextChord").onclick=()=>{var now=performance.now(),sec=(now-last)/1000;last=now;if(count>0&&sec<15){times.push(sec);if(data.bestSwitch===null||sec<data.bestSwitch)data.bestSwitch=sec}count++;data.totalSwitches=(data.totalSwitches||0)+1;today().switches=(today().switches||0)+1;data.lastActive=dateKey();idx=(idx+1)%seq.length;save();updateChord()};$("#newSequence").onclick=()=>{newSeq();toast("已換一組和弦")};
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));today();newSeq();renderAll()
})();