(() => {
  "use strict";
const localStorage=window.gcProfiles?.store||{getItem:key=>window.localStorage.getItem(key),setItem:(key,value)=>window.localStorage.setItem(key,value),removeItem:key=>window.localStorage.removeItem(key)};
  const storage=window.gcStorage;
  const STORE="guitarCoachClassroomNotebookV1",ACTIVE="guitarCoachClassroomActiveV1";
  let tool="●",barreStart=null,active=false,ready=false;
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c));
  const uid=()=>"cg-"+Date.now()+"-"+Math.random().toString(36).slice(2,8);
  const clone=v=>typeof structuredClone==="function"?structuredClone(v):JSON.parse(JSON.stringify(v));
  const load=()=>{if(window.gcNotebook)return window.gcNotebook.list();try{const v=(window.gcSecurity?.parse||JSON.parse)(storage.getItem(STORE)||"[]");return Array.isArray(v)?v:[]}catch(e){return[]}};
  const saveList=list=>window.gcNotebook?window.gcNotebook.replace(list):localStorage.setItem(STORE,JSON.stringify(list));
  function ctx(){const id=$("#teacherLessonForm")?.dataset.classroomNotebookId||storage.getItem(ACTIVE)||"",list=load();return{list,item:list.find(x=>x.id===id)||null}}
  function commit(item,list){item.updatedAt=Date.now();const i=list.findIndex(x=>x.id===item.id);if(i>=0)list[i]=item;else list.push(item);saveList(list);const s=$("#classroomAutoSave");if(s&&!document.getElementById("gcStorageFailure")){const d=new Date();s.textContent="已暫存 "+String(d.getHours()).padStart(2,"0")+":"+String(d.getMinutes()).padStart(2,"0")}}
  function blocks(){return ctx().item?.blocks?.filter(b=>b.type==="chordgrid")||[]}
  function blank(name=""){return{id:uid(),type:"chordgrid",name,baseFret:1,top:Array(6).fill(""),cells:Array.from({length:4},()=>Array(6).fill("")),barres:[],memo:"",createdAt:Date.now()}}
  const defs={C:["X",3,2,0,1,0],G:[3,2,0,0,0,3],Am:["X",0,2,2,1,0],Fmaj7:[1,3,2,0,1,0],F:[1,3,3,2,1,1],D:["X","X",0,2,3,2],Dm:["X","X",0,2,3,1],E:[0,2,2,1,0,0],Em:[0,2,2,0,0,0],A:["X",0,2,2,2,0]};
  function preset(name){const b=blank(name);defs[name].forEach((v,c)=>{if(v==="X")b.top[c]="X";else if(v===0)b.top[c]="O";else b.cells[v-1][c]="●"});if(name==="F")b.barres=[{row:0,start:0,end:5,finger:"1"}];return b}
  function mutate(id,fn,rerender=true){const {list,item}=ctx();if(!item)return;const i=(item.blocks||[]).findIndex(b=>b.id===id);if(i<0)return;const b=clone(item.blocks[i]);fn(b);item.blocks[i]=b;commit(item,list);if(rerender)render();else{const h=$("[data-grid-block='"+id+"'] header strong");if(h)h.textContent=b.name||"未命名和弦"}}
  function add(seed=null){const {list,item}=ctx();if(!item)return;const b=seed?clone(seed):blank();b.id=uid();item.blocks=[...(item.blocks||[]),b];commit(item,list);render();requestAnimationFrame(()=>$("[data-grid-block='"+b.id+"']")?.scrollIntoView({behavior:"smooth",block:"center"}))}
  function remove(id){if(!confirm("刪除這個和弦格？"))return;const {list,item}=ctx();if(!item)return;item.blocks=(item.blocks||[]).filter(b=>b.id!==id);commit(item,list);render()}
  function ensureTab(){const nav=$("#notebookTabs");if(!nav||nav.querySelector("[data-grid-tab]"))return;const b=document.createElement("button");b.type="button";b.dataset.gridTab="1";b.innerHTML="<b>▦</b><span>指法圖</span>";nav.insertBefore(b,nav.querySelector('[data-nb-tab="summary"]')||null);b.onclick=()=>{active=true;barreStart=null;render()}}
  function markBar(b,i,rows=5){const s=Math.min(b.start,b.end),e=Math.max(b.start,b.end),left=(s+.5)/6*100,width=(e-s)/6*100,top=(b.row+.5)/rows*100;return`<button type="button" class="barre-mark" data-grid-barre="${i}" style="left:${left}%;width:${width}%;top:${top}%"><span>${esc(b.finger||"1")}</span></button>`}
  function card(b){const cells=b.cells||Array.from({length:5},()=>Array(6).fill("")),top=b.top||Array(6).fill("");return`<article class="classroom-block chordgrid-card" data-grid-block="${esc(b.id)}"><header><strong>${esc(b.name||"未命名和弦")}</strong><div class="block-actions"><button type="button" data-grid-copy="${esc(b.id)}">⧉</button><button type="button" class="block-delete" data-grid-delete="${esc(b.id)}">×</button></div></header><div class="chordgrid-meta"><label>和弦名稱<input data-grid-name="${esc(b.id)}" value="${esc(b.name||"")}" placeholder="例如 Cmaj7"></label><label>起始品<input type="number" inputmode="numeric" min="1" max="15" data-grid-base="${esc(b.id)}" value="${Math.max(1,Math.min(15,+b.baseFret||1))}"></label></div><div class="chord-diagram-wrap"><div class="string-labels">${["E","A","D","G","B","e"].map(x=>`<span>${x}</span>`).join("")}</div><div class="open-markers">${top.map((v,c)=>`<button type="button" data-grid-top="${esc(b.id)}" data-col="${c}">${esc(v||"·")}</button>`).join("")}</div><div class="fret-number">${b.baseFret>1?esc(b.baseFret)+"fr":""}</div><div class="chord-fret-grid" style="--grid-rows:${cells.length}"><svg class="chord-grid-lines" viewBox="0 0 500 ${cells.length*50}" preserveAspectRatio="none" aria-hidden="true">${Array.from({length:6},(_,i)=>`<line x1="${i*100}" y1="0" x2="${i*100}" y2="${cells.length*50}"/>`).join("")}${Array.from({length:cells.length+1},(_,i)=>`<line x1="0" y1="${i*50}" x2="500" y2="${i*50}" class="${i===0&&(+b.baseFret||1)===1?"nut":""}"/>`).join("")}</svg>${cells.map((r,ri)=>r.map((v,ci)=>`<button type="button" data-grid-cell="${esc(b.id)}" data-row="${ri}" data-col="${ci}" aria-label="第 ${6-ci} 弦第 ${(+b.baseFret||1)+ri} 品${v?"，已標記 "+esc(v):""}">${v?`<span class="grid-dot">${v==="●"?"":esc(v)}</span>`:""}</button>`).join("")).join("")}${(b.barres||[]).map((bar,i)=>markBar(bar,i,cells.length)).join("")}</div></div><div class="chordgrid-hint">上方弦標記：空白 → O 空弦 → X 不彈。橫按：先點起點，再點同一品的終點。</div><label class="block-memo"><span>備註</span><input data-grid-memo="${esc(b.id)}" value="${esc(b.memo||"")}" placeholder="老師提醒、手型重點…"></label></article>`}
  function render(){if(!active)return;ensureTab();const host=$("#classroomWorkspace"),nav=$("#notebookTabs");if(!host||!nav)return;$$('button',nav).forEach(x=>x.classList.remove('active'));nav.querySelector('[data-grid-tab]')?.classList.add('active');const list=blocks();host.innerHTML=`<div class="workspace-head"><div><h3>和弦指法圖</h3><p>由左至右為第 6 至第 1 弦；點弦線記手型，O 空弦、X 不彈。</p></div><button type="button" class="workspace-add" data-grid-add>＋ 新增空白指法圖</button></div><div class="chordgrid-presets"><span>常用</span>${Object.keys(defs).map(x=>`<button type="button" data-grid-preset="${x}">${x}</button>`).join("")}</div><div class="chordgrid-toolbox"><span>填入</span>${["●","1","2","3","4","T"].map(x=>`<button type="button" class="${tool===x?"active":""}" data-grid-tool="${x}">${x}</button>`).join("")}<button type="button" class="${tool==="barre"?"active":""}" data-grid-tool="barre">橫按</button><button type="button" class="${tool==="erase"?"active":""}" data-grid-tool="erase">擦除</button></div>${list.length?`<div class="classroom-blocks chordgrid-blocks">${list.map(card).join("")}</div>`:`<div class="classroom-empty"><strong>還沒有和弦指法圖</strong><span>可直接選上方常用和弦，或新增空白格。</span><button type="button" data-grid-add>＋ 新增空白指法圖</button></div>`}`;bind(host)}
  function bind(host){$$('[data-grid-add]',host).forEach(x=>x.onclick=()=>add());$$('[data-grid-preset]',host).forEach(x=>x.onclick=()=>add(preset(x.dataset.gridPreset)));$$('[data-grid-tool]',host).forEach(x=>x.onclick=()=>{tool=x.dataset.gridTool;barreStart=null;render()});$$('[data-grid-delete]',host).forEach(x=>x.onclick=()=>remove(x.dataset.gridDelete));$$('[data-grid-copy]',host).forEach(x=>x.onclick=()=>{const b=blocks().find(q=>q.id===x.dataset.gridCopy);if(b)add(b)});$$('[data-grid-name]',host).forEach(x=>x.oninput=()=>mutate(x.dataset.gridName,b=>b.name=x.value,false));$$('[data-grid-base]',host).forEach(x=>x.onchange=()=>mutate(x.dataset.gridBase,b=>b.baseFret=Math.max(1,Math.min(15,+x.value||1))));$$('[data-grid-memo]',host).forEach(x=>x.oninput=()=>mutate(x.dataset.gridMemo,b=>b.memo=x.value,false));$$('[data-grid-top]',host).forEach(x=>x.onclick=()=>mutate(x.dataset.gridTop,b=>{const c=+x.dataset.col;b.top=b.top||Array(6).fill("");b.top[c]=b.top[c]===""?"O":b.top[c]==="O"?"X":""}));$$('[data-grid-barre]',host).forEach(x=>x.onclick=()=>{const id=x.closest('[data-grid-block]')?.dataset.gridBlock;mutate(id,b=>b.barres=(b.barres||[]).filter((_,i)=>i!==+x.dataset.gridBarre))});$$('[data-grid-cell]',host).forEach(x=>x.onclick=()=>{const id=x.dataset.gridCell,r=+x.dataset.row,c=+x.dataset.col;if(tool==="barre"){if(!barreStart||barreStart.id!==id||barreStart.row!==r){barreStart={id,row:r,col:c};x.classList.add('barre-start');return}const s=barreStart;barreStart=null;mutate(id,b=>b.barres=[...(b.barres||[]),{row:r,start:s.col,end:c,finger:"1"}]);return}mutate(id,b=>{b.cells=b.cells||Array.from({length:5},()=>Array(6).fill(""));b.cells[r][c]=tool==="erase"?"":(b.cells[r][c]===tool?"":tool)})})}
  function summary(){if(active)return;const tab=$("#notebookTabs [data-nb-tab='summary'].active"),preview=$(".summary-preview");if(!tab||!preview||$("#gridSummaryAddon"))return;const list=blocks();if(!list.length)return;const d=document.createElement('div');d.id='gridSummaryAddon';d.innerHTML=`<b>▦</b><span>和弦格：${list.length} 個${list.some(x=>x.name)?" · "+esc(list.map(x=>x.name).filter(Boolean).join("、")):""}</span>`;preview.appendChild(d)}
  function sync(){if(!$("#classroomNotebook"))return;ensureTab();summary()}
  document.addEventListener('gc:workspace-rendered',()=>{active=false;barreStart=null;sync()});
  sync();
})();
