(() => {
'use strict';
// Local operation controls only. The device owner can still alter or erase browser storage.
const OWNER_HASH='2bc01d7a9319e3c81772c57b90737c70b4ffd149f6115395cd0bf089bf3519b2',CONFIG='guitarCoachLocalAdminV1',REG='guitarCoachProfilesV1',TRASH='guitarCoachRecycleV1';
const DATA=['guitarCoachV1','guitarCoachV2','guitarCoachTeacherDraftV1','guitarCoachClassroomNotebookV1','guitarCoachClassroomActiveV1','guitarCoachNotebookTabV2','guitarCoachStaffPaletteV2','guitarCoachThemeV1'];
const prefix=id=>id==='default'?'':'guitarCoachUser:'+id+':',media=id=>id==='default'?'guitarCoachMediaV1':'guitarCoachMediaV1-'+id;
let secret=null,lastUse=0,busy=false;
const encoder=new TextEncoder(),hex=b=>Array.from(new Uint8Array(b),x=>x.toString(16).padStart(2,'0')).join('');
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))),un64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
function validateFile(f){if(!f||f.type!=='guitar-coach-admin-key'||f.version!==1||f.owner!=='可樂'||f.iterations!==600000||!/^[a-f0-9]{32}$/.test(f.salt)||!/^[a-f0-9]{24}$/.test(f.iv)||typeof f.cipher!=='string'||f.cipher.length>512)throw Error('管理金鑰格式不正確');return f}
async function validSecret(s){return typeof s==='string'&&/^COLA-GC-[a-f0-9]{64}$/.test(s)&&hex(await crypto.subtle.digest('SHA-256',encoder.encode(s)))===OWNER_HASH}
async function key(password,salt){if(typeof password!=='string'||password.length<12||password.length>128)throw Error('管理密碼須為 12 至 128 字元');const material=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt:Uint8Array.from(salt.match(/../g),x=>parseInt(x,16)),iterations:600000},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function wrap(s,password){const salt=hex(crypto.getRandomValues(new Uint8Array(16))),iv=hex(crypto.getRandomValues(new Uint8Array(12)));const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv:Uint8Array.from(iv.match(/../g),x=>parseInt(x,16))},await key(password,salt),encoder.encode(s));return {type:'guitar-coach-admin-key',version:1,owner:'可樂',iterations:600000,salt,iv,cipher:b64(cipher)}}
async function decode(f,password){validateFile(f);let s;try{s=new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:Uint8Array.from(f.iv.match(/../g),x=>parseInt(x,16))},await key(password,f.salt),un64(f.cipher)))}catch(e){throw Error('金鑰或管理密碼不正確')}if(!(await validSecret(s)))throw Error('這不是可樂的管理金鑰');return s}
function isUnlocked(){if(!secret||Date.now()-lastUse>15*60*1000){secret=null;return false}return true}
function assertAdmin(){if(!isUnlocked())throw Error('請先解鎖可樂管理者');lastUse=Date.now()}
async function enroll(code,password){if(localStorage.getItem(CONFIG))throw Error('此裝置已有管理金鑰，請解鎖或匯入原金鑰');if(!(await validSecret(code.trim())))throw Error('專屬啟用碼不正確');const f=await wrap(code.trim(),password);localStorage.setItem(CONFIG,JSON.stringify(f));secret=code.trim();lastUse=Date.now();return f}
async function importKey(file,password){const s=await decode(file,password);localStorage.setItem(CONFIG,JSON.stringify(validateFile(file)));secret=s;lastUse=Date.now()}
async function unlock(password){const f=JSON.parse(localStorage.getItem(CONFIG)||'null');secret=await decode(f,password);lastUse=Date.now()}
async function reverify(password){assertAdmin();const s=await decode(JSON.parse(localStorage.getItem(CONFIG)||'null'),password);if(s!==secret)throw Error('管理金鑰已變更');lastUse=Date.now()}
async function changePassword(oldPassword,newPassword){await reverify(oldPassword);const f=await wrap(secret,newPassword);localStorage.setItem(CONFIG,JSON.stringify(f));return f}
function listUsers(){const p=window.gcProfiles.list();return p.map(x=>({id:x.id,name:x.name}))}
function validIds(ids){const users=listUsers();if(!Array.isArray(ids)||!ids.length||new Set(ids).size!==ids.length||ids.some(id=>!users.some(p=>p.id===id)))throw Error('請勾選有效的使用者');return users.filter(p=>ids.includes(p.id))}
function openDb(name){return new Promise((resolve,reject)=>{const r=indexedDB.open(name);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('lessonMedia'))db.createObjectStore('lessonMedia',{keyPath:'id'}).createIndex('lessonId','lessonId',{unique:false})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('資料庫被其他頁面占用，請關閉其他吉他網站頁面'))})}
function completed(tx){return new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('資料庫操作已中止'))})}
async function trashDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(TRASH,1);r.onupgradeneeded=()=>r.result.createObjectStore('entries',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function trashAction(mode,fn){const db=await trashDb();try{const tx=db.transaction('entries',mode),done=completed(tx),r=fn(tx.objectStore('entries'));let result;r.onsuccess=()=>result=r.result;await done;return result}finally{db.close()}}
async function mediaSnapshot(id){const db=await openDb(media(id));try{const names=Array.from(db.objectStoreNames);if(!names.length)return [];const tx=db.transaction(names,'readonly'),done=completed(tx);const result=await Promise.all(names.map(name=>new Promise((resolve,reject)=>{const store=tx.objectStore(name),r=store.getAll(),k=store.getAllKeys();let values,keys;const finish=()=>{if(values&&keys)resolve({name,keyPath:store.keyPath,autoIncrement:store.autoIncrement,values,keys})};r.onsuccess=()=>{values=r.result;finish()};k.onsuccess=()=>{keys=k.result;finish()};r.onerror=k.onerror=()=>reject(r.error||k.error)})));await done;return result}finally{db.close()}}
async function capture(ids){const users=validIds(ids),rows=[];for(const user of users){const data={};DATA.forEach(k=>data[k]=localStorage.getItem(prefix(user.id)+k));rows.push({...user,data,stores:await mediaSnapshot(user.id)})}const entry={id:crypto.randomUUID(),created:Date.now(),state:'備份完成',users:rows};await trashAction('readwrite',s=>s.add(entry));return entry}
async function clearMedia(id){const db=await openDb(media(id));try{const names=Array.from(db.objectStoreNames);if(!names.length)return;const tx=db.transaction(names,'readwrite'),done=completed(tx);names.forEach(n=>tx.objectStore(n).clear());await done}finally{db.close()}}
async function restoreMedia(user){const db=await openDb(media(user.id));try{for(const s of user.stores){if(!db.objectStoreNames.contains(s.name))throw Error('附件資料庫結構不符，已保留回收備份');const tx=db.transaction(s.name,'readonly'),os=tx.objectStore(s.name);if(JSON.stringify(os.keyPath)!==JSON.stringify(s.keyPath))throw Error('附件索引不符，已停止復原')}
const names=Array.from(db.objectStoreNames);if(!names.length)return;const tx=db.transaction(names,'readwrite'),done=completed(tx);names.forEach(n=>tx.objectStore(n).clear());for(const s of user.stores){const store=tx.objectStore(s.name);s.values.forEach((v,i)=>store.keyPath===null?store.put(v,s.keys[i]):store.put(v))}await done}finally{db.close()}}
async function exclusive(fn){if(busy)throw Error('管理資料操作尚未完成');busy=true;try{if(navigator.locks)return await navigator.locks.request('guitar-coach-data-maintenance',{mode:'exclusive'},fn);return await fn()}finally{busy=false}}
async function recycle(ids,password){await reverify(password);const users=validIds(ids);return exclusive(async()=>{await reverify(password);await window.gcProfiles.prepareMaintenance(ids);let entry;try{for(const user of users)localStorage.setItem('guitarCoachProfileEpoch:'+user.id,crypto.randomUUID());entry=await capture(ids);for(const user of users){await clearMedia(user.id);DATA.forEach(k=>localStorage.removeItem(prefix(user.id)+k))}entry.state='已移至回收區';await trashAction('readwrite',s=>s.put(entry));return entry.id}finally{window.gcProfiles.finishMaintenance(ids)}})}
async function ownCapture(id){if(id!==window.gcProfiles.currentId||!window.gcProfiles.canRead())throw Error('無法備份其他使用者');return capture([id])}
async function restore(id,password){await reverify(password);return exclusive(async()=>{await reverify(password);const entry=await trashAction('readonly',s=>s.get(id));if(!entry)throw Error('回收紀錄不存在');const ids=entry.users.map(u=>u.id);validIds(ids);await window.gcProfiles.prepareMaintenance(ids);try{for(const u of entry.users){localStorage.setItem('guitarCoachProfileEpoch:'+u.id,crypto.randomUUID());await restoreMedia(u);DATA.forEach(k=>u.data[k]===null?localStorage.removeItem(prefix(u.id)+k):localStorage.setItem(prefix(u.id)+k,u.data[k]))}entry.state='已復原（備份保留）';await trashAction('readwrite',s=>s.put(entry))}finally{window.gcProfiles.finishMaintenance(ids)}})}
async function purge(id,password){await reverify(password);return exclusive(async()=>{await reverify(password);await trashAction('readwrite',s=>s.delete(id))})}
async function trashList(){assertAdmin();return (await trashAction('readonly',s=>s.getAll())).map(e=>({id:e.id,created:e.created,state:e.state,names:e.users.map(u=>u.name)}))}
function download(f){const url=URL.createObjectURL(new Blob([JSON.stringify(f,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='可樂_Guitar_Coach_管理金鑰.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}
function mount(){const host=document.getElementById('gcProfilePanel')||document.querySelector('.gc-profile-gate');if(!host||document.getElementById('gcAdminPanel'))return;const panel=document.createElement('details');panel.id='gcAdminPanel';panel.className='gc-admin-panel';panel.innerHTML='<summary>可樂管理者／本機回收區</summary><p>管理金鑰可帶到其他裝置。資料留在本機，不會同步；15 分鐘未使用管理操作會鎖定。</p><p data-admin-state></p><div data-admin-auth><label>首次啟用碼<input type="password" data-admin-code autocomplete="off" placeholder="只有可樂持有的啟用碼"></label><label>管理密碼<input type="password" data-admin-password autocomplete="current-password" maxlength="128" placeholder="至少 12 字元"></label><label>首次設定／新管理密碼確認<input type="password" data-admin-confirm autocomplete="new-password" maxlength="128"></label><div class="gc-profile-row"><button type="button" data-enroll>首次啟用並下載金鑰</button><button type="button" data-admin-unlock>解鎖管理者</button><label class="button">匯入加密管理金鑰<input type="file" data-admin-file accept="application/json,.json"></label></div></div><div data-admin-actions hidden><div class="gc-profile-row"><button type="button" data-export-key>下載管理金鑰</button><button type="button" data-admin-lock>鎖定管理者</button><button type="button" data-admin-change>變更管理密碼</button></div><p>管理操作需再次輸入管理密碼。金鑰檔與密碼請分開保存；忘記密碼需用原啟用碼在新裝置重新建立，舊金鑰不會自動失效。</p><label>新管理密碼<input type="password" data-admin-new autocomplete="new-password" maxlength="128"></label><fieldset><legend>選擇要清除資料的使用者</legend><div data-admin-users></div></fieldset><div class="gc-profile-row"><button type="button" data-select-all>勾選全部</button><button type="button" data-select-none>取消勾選</button><button type="button" data-recycle>將勾選者資料移至回收區</button></div><p>保留使用者名單及個人密碼，清空筆記、練習、照片與錄音。回收區同樣只在這台裝置，不是外部備份；復原會覆蓋該人的現有資料。</p><h3>本機回收區</h3><div data-admin-trash></div><button type="button" data-refresh-trash>重新整理回收區</button></div><p data-admin-status role="status"></p>';host.appendChild(panel);
const $=s=>panel.querySelector(s),message=s=>$('[data-admin-status]').textContent=s,pwd=()=>$('[data-admin-password]').value;
async function refresh(){const on=isUnlocked();$('[data-admin-state]').textContent=on?'可樂管理者：已解鎖':'管理者已鎖定；一般使用者不能管理他人資料';$('[data-admin-actions]').hidden=!on;$('[data-enroll]').hidden=!!localStorage.getItem(CONFIG);if(!on){$('[data-admin-users]').replaceChildren();$('[data-admin-trash]').replaceChildren();return}const rows=listUsers().map(u=>{const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.value=u.id;input.dataset.adminUser='';label.append(input,document.createTextNode(u.name));return label});$('[data-admin-users]').replaceChildren(...rows);await refreshTrash()}
async function refreshTrash(){const rows=await trashList(),box=$('[data-admin-trash]');box.replaceChildren();if(!rows.length){box.textContent='目前沒有回收紀錄';return}for(const row of rows){const el=document.createElement('div');el.className='gc-trash-row';const label=document.createElement('p');label.textContent=new Date(row.created).toLocaleString()+'｜'+row.names.join('、')+'｜'+row.state;el.append(label);for(const [text,action]of [['復原',restore],['永久刪除此回收備份',purge]]){const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=()=>run(async()=>{await reverify(pwd());if(!confirm(action===purge?'永久刪除此回收備份後無法復原，確定？':'復原會覆蓋這些使用者目前的資料，確定？'))return;await action(row.id,pwd());message(action===purge?'回收備份已永久刪除':'資料已復原');await refreshTrash()});el.append(b)}box.append(el)}}
async function run(fn){if(panel.dataset.busy==='true')return;panel.dataset.busy='true';try{await fn()}catch(e){message(e.message)}finally{panel.dataset.busy='false';$('[data-admin-password]').value='';$('[data-admin-code]').value='';$('[data-admin-confirm]').value='';$('[data-admin-new]').value='';if(!isUnlocked())await refresh()}}
$('[data-enroll]').onclick=()=>run(async()=>{if(pwd()!==$('[data-admin-confirm]').value)throw Error('兩次管理密碼不相同');const f=await enroll($('[data-admin-code]').value,pwd());download(f);message('管理者已啟用，請保存下載的加密金鑰');await refresh()});
$('[data-admin-unlock]').onclick=()=>run(async()=>{await unlock(pwd());message('可樂管理者已解鎖');await refresh()});
$('[data-admin-file]').onchange=()=>run(async()=>{const input=$('[data-admin-file]'),file=input.files[0];try{if(!file)return;if(file.size>4096)throw Error('金鑰檔過大');await importKey(JSON.parse(await file.text()),pwd());message('可樂管理金鑰已匯入');await refresh()}finally{input.value=''}});
$('[data-export-key]').onclick=()=>run(async()=>{await reverify(pwd());download(JSON.parse(localStorage.getItem(CONFIG)));message('管理金鑰已下載')});
$('[data-admin-lock]').onclick=()=>{secret=null;refresh();message('管理者已鎖定')};
$('[data-admin-change]').onclick=()=>run(async()=>{if($('[data-admin-new]').value!==$('[data-admin-confirm]').value)throw Error('兩次新管理密碼不相同');download(await changePassword(pwd(),$('[data-admin-new]').value));message('已變更並下載新金鑰；舊金鑰在其他裝置不會自動失效');await refresh()});
$('[data-select-all]').onclick=()=>panel.querySelectorAll('[data-admin-user]').forEach(x=>x.checked=true);$('[data-select-none]').onclick=()=>panel.querySelectorAll('[data-admin-user]').forEach(x=>x.checked=false);
$('[data-recycle]').onclick=()=>run(async()=>{const ids=Array.from(panel.querySelectorAll('[data-admin-user]:checked'),x=>x.value),users=validIds(ids);await reverify(pwd());if(!confirm('將以下使用者資料移至本機回收區？\n'+users.map(u=>u.name).join('、')))return;await recycle(ids,pwd());message('所選使用者的資料已移至回收區');await refreshTrash()});$('[data-refresh-trash]').onclick=()=>run(refreshTrash);panel.addEventListener('toggle',()=>{if(panel.open)refresh().catch(e=>message(e.message))});refresh().catch(e=>message(e.message));
}
window.gcAdmin={enroll,importKey,unlock,changePassword,isUnlocked,recycle,restore,purge,trashList,mount,lock(){secret=null}};
window.gcLocalTrash={captureOwn:ownCapture};
window.addEventListener('storage',e=>{if(e.key===CONFIG){secret=null;const el=document.querySelector('[data-admin-actions]');if(el)el.hidden=true}});
})();
